services:
- docker
script:
- docker build -t cliwrap/gradle .
# Make sure the container works normally
- docker run --rm cliwrap/gradle java -version 2>&1 | grep 'openjdk version "1.8'
# Make sure the container works normally
- docker run --rm cliwrap/gradle gradle --version 2>&1 | grep '^Gradle'
after_success:
- >
  curl -H "Content-Type: application/json"
  --data '{"source_type": "Branch", "source_name": "master"}'
  -X POST
  https://hub.docker.com/api/build/v1/source/d2708ac7-8ce6-40a8-826a-9489fc793a96/trigger/c9eb795e-5e65-4349-95da-4f0d588f2dea/call/
notifications:
  email:
    recipients:
      secure: b32rip4nx8iGUVbuAk632TldE/zNp2XWLvwkLcK1CigpZfP6Md6eMEyyKJn5tRR8mPm/XYCjtMRwrr+uJv0H1iSo++YAaWl467LlkiRspTPav7o7SXBCIqkK17kjWPjzPzA7QdlUuurRJdnXuPPxp7ZuYLpf94xwuOE0xcDLRMF5+3RNlYMKj/NYxE2MUklJNqbF4wh1P/i4G0cLYqP37JIMQTOuow4xSsTGDxnjIkdfZQIFOUnxCx75hCJOVvJXLxVxipWbFzMpWEhJ6RK2s/4OzET7fCEgPJmlKmA9nvaVadNTZhlvdob+40msQ3FDlpviogfvqXIhGmaN4PFKv7QVCCWUkOo/oReb6RjNQQcceeU2R15TFrGIWpFa53HRGrX6KI2zcgx1tTYaZROrMnj0tYfYMdBO/47G2WtmwOcKsEfGszS/5HgSSDoNgBtwECPHxTQrA4acWjcljjrVqpCHvWUZ/Z/PcemKLcZfMjgmtmM4wd2kZJ9rWnZVoZHEVkdZXy2PsooI0U8bfkAS0yG8goPD5XqL5QIh8n0SN4UippuuWuUNUYnFqcK3uwFA2Ix7v3EPm7e9T/HSBWTvMnOoeZ+KIJVYoSyV/aSVGLsk1d9dXKb4BNrw0J0edraRMqxT3Fq1c6bAUEBBivSilnyaMpAP+UqovkTfWFJi1Qc=
